GET http://localhost:3000/api/book

###

POST GET http://localhost:3000/api/book
Cookie: freya_session=bDoWMdRvFeM4Xs9e1a5dhWkFzx4X8nFY; HttpOnly; SameSite=Strict; Path=/; Expires=Tue, 02 Jan 2024 15:32:07 GMT

